### ISSUE TITLE
Run Demo Error

### ISSUE THREAD

**Issue by ronnie-z** [zhang-pengyu/ADRNet#14]
The following error is reported when the demo sequence is run:
UnicodeDecodeError: 'utf-8' codec can't decode bytes…………
Wish your reply!

**Comment by zhang-pengyu** [comment]
Hello, this seems an encoding type error[1,2], just try adding 
```
#!/usr/bin/env python
# coding=utf-8
```
to the begining of the code.
[1] https://blog.csdn.net/weixin_41529093/article/details/111343308
[2] https://blog.csdn.net/qq_36387683/article/details/91374774

If the same error occurs, please provide more details for reproducing it.

**Comment by ronnie-z** [comment]
FAILED: prroi_pooling_gpu_impl.cuda.o
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output prroi_pooling_gpu_impl.cuda.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/include -isystem /home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/include/TH -isystem /home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/miner/anaconda3/envs/zkl/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/miner/zkl/tracking/ADRNet/modules/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
nvcc fatal   : Unsupported gpu architecture 'compute_86'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/home/miner/anaconda3/envs/zkl/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Run_test.py", line 52, in <module>
    run_MDNet()
  File "Run_test.py", line 46, in run_MDNet
    result, fps = run_mdnet(rgb_dir, t_dir, gt[0], gt, seq = [], display=opts['visualize'])
  File "/home/miner/zkl/tracking/ADRNet/tracker.py", line 221, in run_mdnet
    RGB_cropped_image, RGB_cur_image_var = img_crop_model.crop_image(RGB_cur_image, np.reshape(scene_boxes[bidx],(1,4)), crop_img_size)
  File "./modules/img_cropper.py", line 50, in crop_image
    cropped_image = self.forward(cur_image_var, roi)
  File "./modules/img_cropper.py", line 27, in forward
    aligned_image_var = self.roi_align_model(image, roi)
  File "/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./modules/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "./modules/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "./modules/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1407, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_prroi_pooling'

**Comment by zhang-pengyu** [comment]
Please refer to #8 to recompile the Precise ROI pooling

**Comment by itis112** [comment]
> 失败：prroi_pooling_gpu_impl.cuda.o /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output prroi_pooling_gpu_impl.cuda.o.d -DTORCH_EXTENSION_NAME=prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=“gcc” -DPYBIND11_STDLIB=“libstdcpp” -DPYBIND11_BUILD_ABI=“cxxabi1011” -isystem /home/miner/anaconda3/envs/____zkl/lib/python3.7/site-packages/torch/include -isystem /home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/include/torch/csrc/api/____include -isystem /home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/include/TH -isystem /home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/miner/anaconda3/envs/zkl/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS -D__CUDA_NO_HALF_CONVERSIONS-D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86，code=compute_86 -gencode=arch=compute_86，code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/miner/zkl/tracking/ADRNet/modules/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o nvcc 致命：不支持的 gpu 架构“compute_86”忍者： build stopped：子命令失败。回溯（最近一次调用最后一次）：文件“/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py”，第 1673 行，在 _run_ninja_build env=env） 文件“/home/miner/anaconda3/envs/zkl/lib/python3.7/subprocess.py”，第 512 行，在运行 output=stdout， stderr=stderr） 子进程中。CalledProcessError：命令“['ninja'， '-v']' 返回非零退出状态 1。
> 
> 上述异常是导致以下异常的直接原因：
> 
> 回溯（最近一次调用最后一次）： 文件“Run_test.py”，第 52 行，在 run_MDNet（） 中 文件“Run_test.py”，第 46 行，run_MDNet结果中，fps = run_mdnet（rgb_dir， t_dir， gt[0]， gt， seq = []， display=opts['visualize']） 文件“/home/miner/zkl/tracking/ADRNet/tracker.py”，第 221 行，在run_mdnet RGB_cropped_image中，RGB_cur_image_var = img_crop_model.crop_image（RGB_cur_image， np.reshape（scene_boxes[bidx]，（1,4））， crop_img_size） 文件“./modules/img_cropper.py”，第 50 行，crop_image cropped_image = self.forward（cur_image_var， roi） 文件“./modules/img_cropper.py”，第 27 行，前向aligned_image_var = self.roi_align_model（image， roi） 文件“/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/nn/modules/module.py”，第 889 行，在_call_impl结果 = self.forward（*input， **kwargs） 文件“./modules/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py”，第 28 行，前向返回prroi_pool2d（features， rois， self.pooled_height， self.pooled_width， self.spatial_scale） 文件 “./modules/PreciseRoIPooling/pytorch/prroi_pool/functional.py”，第 44 行，前向_prroi_pooling = _import_prroi_pooling（） 文件 “./modules/PreciseRoIPooling/pytorch/prroi_pool/functional.py”，第 33 行，在 _import_ 中prroi_pooling verbose=True 文件 “/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py”，第 1091 行，加载 keep_intermediates=keep_intermediates） 文件“/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py”，第 1302 行，_jit_compile is_standalone=is_standalone）文件“/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py”，第 1407 行，_write_ninja_file_and_build_library error_prefix=f“构建扩展”{name}“时出错） 文件”/home/miner/anaconda3/envs/zkl/lib/python3.7/site-packages/torch/utils/cpp_extension.py“，第 1683 行，_run_ninja_build 从 e 中引发 RuntimeError（message）：构建扩展”_prroi_pooling“时出错

你好，请问你解决这个问题了吗？我也遇到这个错误了，一直没有解决
